#!/bin/sh
# vim:et:ft=sh:sts=4:sw=4
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

if ! sed -i '' 's/^GITDRIP_VERSION=.*$/GITDRIP_VERSION='$1'/g' git-drip-version; then
	echo "Could not replace GITDRIP_VERSION variable." >&2
	exit 2
fi

git add git-drip-version
git commit -m "Bumped version number to $1" git-drip-version
